[package]
name = "kv"
version = "0.1.0"
authors = ["Brian Ketelsen <mail@bjk.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
